### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by thedigitalstockade** [AnnMarieW/dash-bootstrap-layout-templates#11]
Great util for creating quick layouts.
Very well conceived.

Problem anytime the aio_theme_changer  is called.
Happens in:

demo_app
l8-with-callbacks.
theme_switch1
theme_switch2

error:

ModuleNotFoundError: No module named 'aio.aio_theme_changer'

**Comment by AnnMarieW** [comment]
Hi @thedigitalstockade 

Glad you like this project.  The "layout templates" was new a concept I was playing with a while ago.  The purpose was to provide a low code solution to make it easier for people new to Dash get started.   However, I decided not to pursue the layout templates after getting some valid critical feedback on the early design.  This library is no longer being maintained.

However, many things that started here have been moved to other projects.   Please see:
- [dash-bootstrap-templates library](https://github.com/AnnMarieW/dash-bootstrap-templates) for the theme change components, Bootstrap themed figure templates, and the stylesheet for updating the `dash-core-components` and the `DataTable` with a Bootstrap theme.
    -  on-line docs and demo  available here:  https://hellodash.pythonanywhere.com/theme_explorer
    
- I started working on a way to simplify making multi-page apps in one of the branches here.  That concept started the collaboration with Plotly to develop the "pages" feature: https://community.plotly.com/t/introducing-dash-pages-a-dash-2-x-feature-preview/57775
    - on-line docs and demo available here:  https://dashlabs.pythonanywhere.com/

For low-code layouts, I recommend checking out the new dash library developed by Snehil Vijay : [dash-mantine-components](https://github.com/snehilvj/dash-mantine-components)
 - You can find the docs here:  https://www.dash-mantine-components.com/

**Comment by thedigitalstockade** [comment]
Thanks for the great followup,
that's a nicely curated list of goodies!
M
